## Jekyll configuration
safe: false
pygments: true
auto: false
markdown: kramdown
permalink: date
exclude: ["Rakefile", "Gemfile", "Gemfile.lock", "index.html.haml"]

## Site preference
title: Undefined Title
paths:
  icon: /assets/img/icon
  image: /assets/img
  vendor: /vendor
  css: /assets/css
author:
  name: Tomotaka Sakuma
  emai: noreply
