## Jekyll configuration
safe: false
pygments: true
auto: false
markdown: kramdown
permalink: date
exclude: ["Rakefile", "Gemfile", "Gemfile.lock", "index.html.haml"]

## Site preference
title: Undefined Title
images:
  url: https://s3-ap-northeast-1.amazonaws.com/tmtk75.github.com
icons:
  url: https://s3-ap-northeast-1.amazonaws.com/tmtk75.github.com/icons
vendor:
  url: /vendor
css:
  url: /assets/css
js:
  url: /assets/js
author:
  name: Tomotaka Sakuma
socials:
  twitter:
    url: https://twitter.com/tmtk75
  facebook:
    url: https://www.facebook.com/tomotaka.sakuma
  github:
    url: https://github.com/tmtk75
  googleplus:
    url: https://plus.google.com/u/0/112810316775699020282/
  linkedin:
    url: http://www.linkedin.com/profile/view?id=88237980&trk=tab_pro
  zerply:
    url: https://zerply.com/tmtk
