## Jekyll configuration
safe: true
pygments: true
auto: false
markdown: redcarpet
permalink: date
encoding: utf-8
exclude: ["Rakefile"]

redcarpet:
  extensions: ['autolink', 'tables']


## Site preference
title: Undefined Title
url: http://tmtk75.github.io
images:
  url: https://s3-ap-northeast-1.amazonaws.com/tmtk75.github.com
icons:
  url: https://s3-ap-northeast-1.amazonaws.com/tmtk75.github.com/icons
public:
  url: /public
css:
  url: /assets/css
js:
  url: /assets/js
author:
  name: Tomotaka Sakuma
socials:
  twitter:
    url: https://twitter.com/tmtk75
  facebook:
    url: https://www.facebook.com/tomotaka.sakuma
  github:
    url: https://github.com/tmtk75
  googleplus:
    url: https://plus.google.com/u/0/112810316775699020282/
  linkedin:
    url: http://www.linkedin.com/profile/view?id=88237980&trk=tab_pro
  zerply:
    url: https://zerply.com/tmtk
