## Jekyll configuration
safe: false
pygments: true
auto: false
markdown: kramdown
permalink: date
exclude: ["Rakefile", "Gemfile", "Gemfile.lock", "index.html.haml"]

## Site preference
title: Undefined Title
images:
  url: https://s3-ap-northeast-1.amazonaws.com/tmtk75.github.com
icons:
  url: https://s3-ap-northeast-1.amazonaws.com/tmtk75.github.com/icons
paths:
  vendor: /vendor
  css: /assets/css
author:
  name: Tomotaka Sakuma
  emai: noreply
profile:
  social:
    twitter: https://twitter.com/tmtk75
    facebook: https://www.facebook.com/tomotaka.sakuma
    github: https://github.com/tmtk75
    googleplus: https://plus.google.com/u/0/112810316775699020282/
    linkedin: http://www.linkedin.com/profile/view?id=88237980&trk=tab_pro
    zerply: https://zerply.com/tmtk
