## Jekyll configuration
safe: false
pygments: true
auto: false
markdown: kramdown
permalink: date
exclude: ["Rakefile", "Gemfile", "index.haml"]

## Site preference
title: Undefined Title
location: http://tmtk75.github.com
paths:
  image: /img
  vendor: /vendor
  css: /css
author:
  name: Tomotaka Sakuma
  emai: noreply
